
import Layout from '../../Layout/Layout';
import { IoFolderOpenOutline } from "react-icons/io5";
import { FaAngleRight } from "react-icons/fa";
import { Link } from 'react-router-dom';

const MetadataList = () => {
    const data = [
        {
            id: 1,
            title: "Population Statistics 2023",
            description: "Metadata for population demographics and trends for the year 2023.",
            keywords: ["population", "demographics", "2023"],
            category: "Demographics",
            author: "National Statistics Department",
            creationDate: "2023-01-15",
            source: "National Data Repository",
            publisher: "Statistics Authority",
            publicationDate: "2023-02-01",
            language: "English",
            accessLevel: "Public",
            license: "Open Data",
            url: "https://data.gov/population-2023",
            format: "CSV",
            size: "1.2MB",
            spatialCoverage: "Global",
            temporalCoverage: "2023",
            status: "Aktif",
        },
        {
            id: 2,
            title: "Urban Development Plan",
            description: "Details of urban development initiatives and city planning data.",
            keywords: ["urban", "development", "city planning"],
            category: "Urban Planning",
            author: "Urban Development Authority",
            creationDate: "2022-11-20",
            source: "City Planning Office",
            publisher: "Urban Development Authority",
            publicationDate: "2022-12-10",
            language: "English",
            accessLevel: "Restricted",
            license: "Proprietary",
            url: "https://cityplanning.gov/urban-plan",
            format: "PDF",
            size: "5.4MB",
            spatialCoverage: "City-Level",
            temporalCoverage: "2022-2025",
            status: "Aktif",
        },
        {
            id: 3,
            title: "Climate Change Impact Analysis",
            description: "Comprehensive analysis of climate change effects over the last decade.",
            keywords: ["climate change", "environment", "impact analysis"],
            category: "Environment",
            author: "Environmental Protection Agency",
            creationDate: "2023-06-01",
            source: "Environmental Database",
            publisher: "EPA",
            publicationDate: "2023-07-15",
            language: "English",
            accessLevel: "Public",
            license: "Creative Commons",
            url: "https://epa.gov/climate-impact",
            format: "JSON",
            size: "3.8MB",
            spatialCoverage: "National",
            temporalCoverage: "2013-2023",
            status: "Aktif",
        },
        {
            id: 4,
            title: "Land Use Data 2024",
            description: "Detailed information on land use patterns for the upcoming year.",
            keywords: ["land use", "geography", "2024"],
            category: "Geography",
            author: "Geospatial Data Agency",
            creationDate: "2023-09-10",
            source: "Geospatial Database",
            publisher: "Geospatial Data Agency",
            publicationDate: "2023-09-20",
            language: "English",
            accessLevel: "Confidential",
            license: "Proprietary",
            url: "https://geoagency.gov/land-use-2024",
            format: "GeoJSON",
            size: "2.7MB",
            spatialCoverage: "Regional",
            temporalCoverage: "2024",
            status: "Aktif",
        },
        {
            id: 5,
            title: "Housing Development Statistics 2023",
            description: "Comprehensive statistics on housing developments, including urban and rural areas.",
            keywords: ["housing", "development", "2023"],
            category: "Construction",
            author: "Housing and Urban Development Authority",
            creationDate: "2023-02-01",
            source: "Housing Data Repository",
            publisher: "Urban Housing Ministry",
            publicationDate: "2023-03-01",
            language: "English",
            accessLevel: "Public",
            license: "Open Data",
            url: "https://housing.gov/housing-2023",
            format: "CSV",
            size: "2.5MB",
            spatialCoverage: "National",
            temporalCoverage: "2023",
            status: "Aktif",
        },
        {
            id: 6,
            title: "Affordable Housing Projects 2024",
            description: "Data on planned affordable housing projects for the year 2024.",
            keywords: ["housing", "affordable", "2024"],
            category: "Housing",
            author: "Affordable Housing Initiative",
            creationDate: "2023-08-10",
            source: "Affordable Housing Database",
            publisher: "Housing Ministry",
            publicationDate: "2023-09-05",
            language: "English",
            accessLevel: "Restricted",
            license: "Proprietary",
            url: "https://housing.gov/affordable-2024",
            format: "PDF",
            size: "4.1MB",
            spatialCoverage: "Regional",
            temporalCoverage: "2024",
            status: "Aktif",
        },
        {
            id: 7,
            title: "Construction Industry Growth Report 2022",
            description: "Insights and trends in the construction industry's growth in 2022.",
            keywords: ["construction", "growth", "industry"],
            category: "Growth",
            author: "Construction Authority",
            creationDate: "2022-10-15",
            source: "Construction Data Repository",
            publisher: "Construction Authority",
            publicationDate: "2022-11-20",
            language: "English",
            accessLevel: "Public",
            license: "Creative Commons",
            url: "https://construction.gov/growth-2022",
            format: "PDF",
            size: "3.9MB",
            spatialCoverage: "National",
            temporalCoverage: "2022",
            status: "Aktif",
        },
        {
            id: 8,
            title: "Urban Growth and Expansion Analysis 2023",
            description: "Analysis of urban growth patterns and expansion plans.",
            keywords: ["urban", "growth", "expansion"],
            category: "Urban Planning",
            author: "Urban Growth Monitoring Authority",
            creationDate: "2023-04-01",
            source: "Urban Data Repository",
            publisher: "Urban Planning Authority",
            publicationDate: "2023-04-15",
            language: "English",
            accessLevel: "Public",
            license: "Open Data",
            url: "https://urbanplanning.gov/growth-2023",
            format: "GeoJSON",
            size: "6.5MB",
            spatialCoverage: "City-Level",
            temporalCoverage: "2023",
            status: "Aktif",
        },
        {
            id: 9,
            title: "Infrastructure Development Plan 2025",
            description: "A strategic plan outlining major infrastructure developments through 2025.",
            keywords: ["infrastructure", "development", "2025"],
            category: "Construction",
            author: "Infrastructure Development Authority",
            creationDate: "2023-06-20",
            source: "National Infrastructure Database",
            publisher: "Infrastructure Ministry",
            publicationDate: "2023-07-10",
            language: "English",
            accessLevel: "Restricted",
            license: "Proprietary",
            url: "https://infrastructure.gov/plan-2025",
            format: "PDF",
            size: "5.2MB",
            spatialCoverage: "National",
            temporalCoverage: "2023-2025",
            status: "Aktif",
        },
        {
            id: 10,
            title: "Land Development Projects 2024",
            description: "Data on key land development projects scheduled for 2024.",
            keywords: ["land", "development", "2024"],
            category: "Construction",
            author: "Land Development Authority",
            creationDate: "2023-05-15",
            source: "Land Development Database",
            publisher: "National Land Agency",
            publicationDate: "2023-06-01",
            language: "English",
            accessLevel: "Public",
            license: "Creative Commons",
            url: "https://landdevelopment.gov/projects-2024",
            format: "CSV",
            size: "3.7MB",
            spatialCoverage: "Regional",
            temporalCoverage: "2024",
            status: "Aktif",
        },
        {
            id: 11,
            title: "Construction Workforce Statistics 2023",
            description: "Statistics on the workforce engaged in the construction sector in 2023.",
            keywords: ["workforce", "construction", "statistics"],
            category: "Labor",
            author: "Labor Market Authority",
            creationDate: "2023-01-25",
            source: "Construction Labor Database",
            publisher: "Labor Ministry",
            publicationDate: "2023-02-10",
            language: "English",
            accessLevel: "Public",
            license: "Open Data",
            url: "https://labormarket.gov/construction-workforce-2023",
            format: "CSV",
            size: "2.3MB",
            spatialCoverage: "National",
            temporalCoverage: "2023",
            status: "Aktif",
        },
        {
            id: 12,
            title: "Residential Growth Report 2023",
            description: "A detailed report on residential growth trends in 2023.",
            keywords: ["residential", "growth", "housing"],
            category: "Housing",
            author: "Residential Planning Bureau",
            creationDate: "2023-07-05",
            source: "Residential Data Repository",
            publisher: "Housing Ministry",
            publicationDate: "2023-08-01",
            language: "English",
            accessLevel: "Public",
            license: "Open Data",
            url: "https://housing.gov/residential-growth-2023",
            format: "PDF",
            size: "4.5MB",
            spatialCoverage: "City-Level",
            temporalCoverage: "2023",
            status: "Aktif",
        },
        {
            id: 13,
            title: "Smart City Construction Projects 2024",
            description: "Details of ongoing and upcoming smart city construction projects.",
            keywords: ["smart city", "construction", "projects"],
            category: "Urban Planning",
            author: "Smart City Initiative",
            creationDate: "2023-09-12",
            source: "Smart City Database",
            publisher: "Urban Development Ministry",
            publicationDate: "2023-10-01",
            language: "English",
            accessLevel: "Public",
            license: "Open Data",
            url: "https://smartcity.gov/construction-2024",
            format: "GeoJSON",
            size: "6.2MB",
            spatialCoverage: "City-Level",
            temporalCoverage: "2024",
            status: "Aktif",
        },
        {
            id: 14,
            title: "Urban Housing Growth Forecast 2024-2026",
            description: "Forecast data on urban housing growth for the next three years.",
            keywords: ["housing", "growth", "forecast"],
            category: "Housing",
            author: "Housing and Urban Growth Department",
            creationDate: "2023-10-20",
            source: "Urban Growth Database",
            publisher: "National Statistics Bureau",
            publicationDate: "2023-11-01",
            language: "English",
            accessLevel: "Restricted",
            license: "Proprietary",
            url: "https://housing.gov/growth-forecast-2024-2026",
            format: "CSV",
            size: "3.0MB",
            spatialCoverage: "National",
            temporalCoverage: "2024-2026",
            status: "Aktif",
        },
    ];

    return (
        <Layout title='Senarai Data Tersedia' subtitle='Senarai data tersedia untuk kemaskini metadata.'>
            <hr className="h-px my-4 bg-gray-200 border-0 dark:bg-gray-700" />
            <div className="grid grid-cols-3 gap-6 mt-8">
                {data.map((item, index) => (
                    <div className=" px-4 py-6 rounded-lg shadow-lg hover:shadow-2xl transition-all ease-in-out duration-75" key={index}>
                        <div className="flex gap-4 items-center">
                            <IoFolderOpenOutline className='text-[#2196F3] text-6xl' />
                            <h2 className='text-gray-700 font-semibold tracking-wider'>{item.title}</h2>
                        </div>
                        <p className='text-gray-600 text-sm my-4'>{item.description}</p>
                        <div className="flex justify-end mt-5">
                            {/* <p className='text-gray-400 text-xs my-4'>7 Metadata</p> */}
                            <Link to="/metadata-detail">
                                <button className='text-sm flex gap-3 items-center text-gray-600 hover:text-[#2196F3] transition-all ease-in-out duration-75'>Papar Meta Data <FaAngleRight /></button>
                            </Link>
                        </div>
                    </div>
                ))}
            </div>
        </Layout>
    )
}

export default MetadataList